// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: MJWinStreakBallActivity.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace MJWinStreakBallActivity
{

    [global::ProtoBuf.ProtoContract()]
    public partial class OtherStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uin")]
        public uint Uin { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"status")]
        public int Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Reward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_id")]
        public int ItemId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"item_num")]
        public int ItemNum { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"gender")]
        public int Gender { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WinStreakReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"reward")]
        public Reward Reward { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cur_prog")]
        public int CurProg { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"max_prog")]
        public int MaxProg { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReviveInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"require_diamond")]
        public int RequireDiamond { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"revive_with_ads")]
        public int ReviveWithAds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WinStreakInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"win_streak")]
        public int WinStreak { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cur_hp")]
        public int CurHp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"max_hp")]
        public int MaxHp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"win_streak_reward")]
        public global::System.Collections.Generic.List<WinStreakReward> WinStreakRewards { get; } = new global::System.Collections.Generic.List<WinStreakReward>();

        [global::ProtoBuf.ProtoMember(5, Name = @"is_vip")]
        public int IsVip { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"status")]
        public int Status { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"last_update_time")]
        public long LastUpdateTime { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"duration")]
        public long Duration { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"refresh_time")]
        public long RefreshTime { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"revive_info")]
        public ReviveInfo ReviveInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExchangeItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reward")]
        public Reward Reward { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"token_require")]
        public int TokenRequire { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"cur_exchange")]
        public int CurExchange { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"max_exchange")]
        public int MaxExchange { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"status")]
        public int Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExchangeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cur_token")]
        public int CurToken { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exchange_item")]
        public global::System.Collections.Generic.List<ExchangeItem> ExchangeItems { get; } = new global::System.Collections.Generic.List<ExchangeItem>();

        [global::ProtoBuf.ProtoMember(3, Name = @"start_time")]
        public long StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"end_time")]
        public long EndTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDetailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"act_id")]
        public int ActId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"other_uins", IsPacked = true)]
        public uint[] OtherUins { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"open_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OpenKey { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"pf_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PfKey { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"pf")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Pf { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"pay_token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PayToken { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDetailRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"act_id")]
        public int ActId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"start_time")]
        public long StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"end_time")]
        public long EndTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"win_streak_info")]
        public WinStreakInfo WinStreakInfo { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"exchange_info")]
        public ExchangeInfo ExchangeInfo { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"other_status")]
        public global::System.Collections.Generic.List<OtherStatus> OtherStatus { get; } = new global::System.Collections.Generic.List<OtherStatus>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClaimWinStreakBallReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"act_id")]
        public int ActId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"open_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OpenKey { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"pf_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PfKey { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"pf")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Pf { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"pay_token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PayToken { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClaimWinStreakBallRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"act_id")]
        public int ActId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"result")]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"win_streak_info")]
        public WinStreakInfo WinStreakInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExchangeReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"act_id")]
        public int ActId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"open_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OpenKey { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"pf_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PfKey { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"pf")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Pf { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"pay_token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PayToken { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExchangeRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"act_id")]
        public int ActId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"result")]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"exchange_info")]
        public ExchangeInfo ExchangeInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AdsCallBackReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"act_id")]
        public int ActId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"open_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OpenKey { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"pf_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PfKey { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"pf")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Pf { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"pay_token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PayToken { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AdsCallBackRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"act_id")]
        public int ActId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"result")]
        public int Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameEndNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"win_streak_info")]
        public WinStreakInfo WinStreakInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum ErrorCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS")]
        Success = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PARAM_ERROR")]
        ParamError = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CONFIG_NOT_FOUND")]
        ConfigNotFound = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"AMS_PARAM_REQUIRE")]
        AmsParamRequire = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"OPEN_ID_REQUIRE")]
        OpenIdRequire = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"EXPRESS_ITEM_FAILED")]
        ExpressItemFailed = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"ACTIVITY_END")]
        ActivityEnd = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_CONFIG")]
        InvalidConfig = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"SYSTEM_ERROR")]
        SystemError = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"SAVE_DATA_FAILED")]
        SaveDataFailed = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"QUERY_DATA_FAILED")]
        QueryDataFailed = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"REWARD_IS_RECEIVED")]
        RewardIsReceived = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"WHITE_LIST_AUTH_FAILED")]
        WhiteListAuthFailed = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"NO_QUALIFIER")]
        NoQualifier = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"REWARD_UNACHIEVED")]
        RewardUnachieved = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"REWARD_TIMEOUT")]
        RewardTimeout = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"REWARD_NOT_FOUND")]
        RewardNotFound = 16,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum WinStreakStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"WIN_STREAK_STATUS_NONE")]
        WinStreakStatusNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"WIN_STREAK_STATUS_NORMAL")]
        WinStreakStatusNormal = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"WIN_STREAK_STATUS_CAN_REVIVE")]
        WinStreakStatusCanRevive = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"WIN_STREAK_STATUS_FAILED")]
        WinStreakStatusFailed = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ExchangeStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EXCHANGE_STATUS_NONE")]
        ExchangeStatusNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EXCHANGE_STATUS_CAN_EXCHANGE")]
        ExchangeStatusCanExchange = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"EXCHANGE_STATUS_NOT_ENOUGH_TO_EXCHANGE")]
        ExchangeStatusNotEnoughToExchange = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"EXCHANGE_STATUS_OWNED")]
        ExchangeStatusOwned = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
